const Fear = require('@feardread/fear');

async function main() {
    const server = new Fear.FearServer();

    server.initialize({
            root: __dirname,
            app: '/public',
            build: 'public',
            basePath: ''
        })
        .then(() => { 
          server.fear.getLogger().warn('Running FEAR AI Agent Builder');
          server.startServer().catch((err) => { process.exit(1) })
        })
        .catch((error) => { process.exit(1);});
}

// Handle top-level errors
main().catch((error) => {
    console.error('Unhandled error in main:', error);
    process.exit(1);
});


const express = require('express');
const path = require('path');

const app = express();
app.use(express.json());
app.use(express.static('public'));

app.post('/generate', (req, res) => {
  const { formData } = req.body;

  const toolImplementations = {
    web_search: `
async function webSearch(query) {
  // Implement web search functionality
  console.log('Searching for:', query);
  return { results: [] };
}`,
    file_read: `
const fs = require('fs').promises;

async function readFile(path) {
  try {
    const content = await fs.readFile(path, 'utf8');
    return { success: true, content };
  } catch (error) {
    return { success: false, error: error.message };
  }
}`,
    calculator: `
function calculate(expression) {
  try {
    return { result: eval(expression) };
  } catch (error) {
    return { error: 'Invalid expression' };
  }
}`,
    database: `
async function queryDatabase(query) {
  // Implement database query functionality
  console.log('Querying database:', query);
  return { rows: [] };
}`
  };

  const selectedTools = (formData.tools || []).map(t => toolImplementations[t] || '').join('\n');

  const serverCode = `// ${formData.agentName || 'Custom AI Agent'}
// Generated by AI Agent Builder
// ${formData.agentDescription || 'No description provided'}

require('dotenv').config();
const express = require('express');
const Anthropic = require('@anthropic-ai/sdk');

const app = express();
app.use(express.json());
app.use(express.static('public'));

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || '${formData.apiKey || ''}'
});

const AGENT_CONFIG = {
  name: '${formData.agentName || 'Custom Agent'}',
  description: '${formData.agentDescription || 'AI Assistant'}',
  personality: '${formData.personality || 'professional'}',
  model: '${formData.model || 'claude-sonnet-4-20250514'}'
};

const SYSTEM_PROMPT = \`You are \${AGENT_CONFIG.name}, \${AGENT_CONFIG.description}.
Your primary function is: ${formData.primaryFunction || 'assist users with their requests'}.
Personality: \${AGENT_CONFIG.personality}.
${(formData.tools || []).length > 0 ? `Available tools: ${formData.tools.join(', ')}` : ''}
\`;
${selectedTools}

app.post('/chat', async (req, res) => {
  try {
    const { message, conversationHistory = [] } = req.body;

    const messages = [
      ...conversationHistory,
      { role: 'user', content: message }
    ];

    const response = await anthropic.messages.create({
      model: AGENT_CONFIG.model,
      max_tokens: 1024,
      system: SYSTEM_PROMPT,
      messages: messages
    });

    const assistantMessage = response.content[0].text;

    res.json({
      success: true,
      response: assistantMessage,
      conversationHistory: [
        ...messages,
        { role: 'assistant', content: assistantMessage }
      ]
    });
  } catch (error) {
    console.error('Error:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

// Serve the frontend
app.get('/', (req, res) => {
  res.send(\`
<!DOCTYPE html>
<html>
<head>
  <title>\${AGENT_CONFIG.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 20px;
    }
    .container {
      background: white;
      border-radius: 20px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
      width: 100%;
      max-width: 800px;
      height: 600px;
      display: flex;
      flex-direction: column;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 20px;
      border-radius: 20px 20px 0 0;
      text-align: center;
    }
    .chat-container {
      flex: 1;
      overflow-y: auto;
      padding: 20px;
      display: flex;
      flex-direction: column;
      gap: 15px;
    }
    .message {
      padding: 12px 16px;
      border-radius: 12px;
      max-width: 70%;
      word-wrap: break-word;
    }
    .user-message {
      background: #667eea;
      color: white;
      align-self: flex-end;
    }
    .assistant-message {
      background: #f0f0f0;
      color: #333;
      align-self: flex-start;
    }
    .input-container {
      padding: 20px;
      border-top: 1px solid #eee;
      display: flex;
      gap: 10px;
    }
    input {
      flex: 1;
      padding: 12px;
      border: 2px solid #ddd;
      border-radius: 10px;
      font-size: 16px;
    }
    button {
      padding: 12px 24px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      border: none;
      border-radius: 10px;
      cursor: pointer;
      font-size: 16px;
      font-weight: 600;
    }
    button:hover { opacity: 0.9; }
    button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>\${AGENT_CONFIG.name}</h1>
      <p>\${AGENT_CONFIG.description}</p>
    </div>
    <div class="chat-container" id="chatContainer"></div>
    <div class="input-container">
      <input type="text" id="messageInput" placeholder="Type your message..." />
      <button onclick="sendMessage()" id="sendBtn">Send</button>
    </div>
  </div>

  <script>
    let conversationHistory = [];

    async function sendMessage() {
      const input = document.getElementById('messageInput');
      const message = input.value.trim();
      if (!message) return;

      const sendBtn = document.getElementById('sendBtn');
      sendBtn.disabled = true;
      
      addMessage(message, 'user');
      input.value = '';

      try {
        const response = await fetch('/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ message, conversationHistory })
        });

        const data = await response.json();
        
        if (data.success) {
          addMessage(data.response, 'assistant');
          conversationHistory = data.conversationHistory;
        } else {
          addMessage('Error: ' + data.error, 'assistant');
        }
      } catch (error) {
        addMessage('Error: ' + error.message, 'assistant');
      }

      sendBtn.disabled = false;
    }

    function addMessage(text, type) {
      const container = document.getElementById('chatContainer');
      const div = document.createElement('div');
      div.className = \`message \${type}-message\`;
      div.textContent = text;
      container.appendChild(div);
      container.scrollTop = container.scrollHeight;
    }

    document.getElementById('messageInput').addEventListener('keypress', (e) => {
      if (e.key === 'Enter') sendMessage();
    });
  </script>
</body>
</html>
  \`);
});

const PORT = process.env.PORT || ${formData.port || '3000'};
app.listen(PORT, () => {
  console.log(\`🤖 \${AGENT_CONFIG.name} running on http://localhost:\${PORT}\`);
  console.log(\`📝 Description: \${AGENT_CONFIG.description}\`);
  console.log(\`🎭 Personality: \${AGENT_CONFIG.personality}\`);
});
`;

  const packageJson = {
    name: (formData.agentName || 'custom-ai-agent').toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: formData.agentDescription || 'Custom AI Agent',
    main: 'server.js',
    scripts: {
      start: 'node server.js',
      dev: 'nodemon server.js'
    },
    dependencies: {
      '@anthropic-ai/sdk': '^0.32.0',
      'express': '^4.18.2',
      'dotenv': '^16.3.1'
    },
    devDependencies: {
      'nodemon': '^3.0.1'
    }
  };

  const readme = `# ${formData.agentName || 'Custom AI Agent'}

${formData.agentDescription || 'AI Agent generated by AI Agent Builder'}

## Setup

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Create a \`.env\` file:
\`\`\`
ANTHROPIC_API_KEY=your_api_key_here
PORT=${formData.port || '3000'}
\`\`\`

3. Run the agent:
\`\`\`bash
npm start
\`\`\`

4. Open http://localhost:${formData.port || '3000'} in your browser

## Features

- **Primary Function**: ${formData.primaryFunction || 'General assistance'}
- **Personality**: ${formData.personality || 'professional'}
- **Model**: ${formData.model || 'claude-sonnet-4-20250514'}
${(formData.tools || []).length > 0 ? `- **Tools**: ${formData.tools.join(', ')}` : ''}

## Configuration

Edit the \`AGENT_CONFIG\` object in \`server.js\` to customize the agent's behavior.
`;

  const envExample = `ANTHROPIC_API_KEY=your_api_key_here\nPORT=${formData.port || '3000'}`;

  res.json({
    success: true,
    files: {
      'server.js': serverCode,
      'package.json': JSON.stringify(packageJson, null, 2),
      'README.md': readme,
      '.env.example': envExample
    }
  });
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => {
  console.log(`🚀 AI Agent Builder running on http://localhost:${PORT}`);
});