export const FAILED_REQUEST = "AUTH_FAILED_REQUEST";
export const LOADING_REQUEST = "AUTH_LOADING_REQUEST";

export const LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
